* Mapping Meditation Project

We are mapping meditation 'space' using consumer EEG (Muse), powered by open-source AI analysis, made free to all meditators to help their journey. 

Early results showed that strong meditators (> 5 year experience) have consistent, large gamma-wave increases at similar parts of their brains. Different meditation traditions targeted different parts of the brain.

Currently we have an Android app for recording EEG during meditation, paired with a companion website which analyzes the data, highlighting typical changes of strong meditation.

Long-term participants are thrilled with their results. Simply exploring their data after each meditation, comparing their results with previous results and with other particpants, helped them identify important moments during their meditation, increasing their confident, resulting in rapid progress. 

Various companies are getting onboard with EEG for meditation analysis - but this project is entirely free and open-source, not participating in capitalist incentives or taking any funding whatsoever, in order to preserve the spiritual goals of the project.

* Early Results

Daniel Ingram, a meditation teacher and author, is providing ongoing recordings of his practice, along with phenomenological tags to help demonstrate the potential of this method. 
